"""Copy `src/xgb_model_params.json` into the block `index.html` ships with.

Same rationale as `sync_deployed_params.py`: the page is a single static file
and cannot read JSON off disk at runtime, so the tree ensemble travels in as
a generated block of JS, not a hand-typed one. Re-running this script replaces
that block in place, between two marker comments, so retraining never leaves
a stale copy of the trees sitting next to a fresh one.
"""

import io
import json
import os
import re
import sys

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARAMS = os.path.join(BASE, 'src', 'xgb_model_params.json')
HTML = os.path.join(BASE, 'index.html')
CRLF = '\r\n'

BEGIN = '        // --- XGBoost reject-inference signal (generated by src/sync_xgb_params.py) ---'
END = '        // --- end XGBoost signal ---'

# Anchor to insert after on a first run, when no BEGIN/END block exists yet:
# the end of the SCALER block that sync_deployed_params.py also targets.
ANCHOR = re.compile(r'(        const SCALER = \{.*?\n        \};\n)', re.S)


def load(path):
    raw = io.open(path, encoding='utf-8', newline='').read()
    return raw.replace(CRLF, '\n'), (CRLF in raw)


def save(path, text, crlf):
    if crlf:
        text = text.replace('\n', CRLF)
    io.open(path, 'w', encoding='utf-8', newline='').write(text)


def build_block(p):
    lines = [
        BEGIN,
        '        // Source of truth: src/xgb_model_params.json, written by',
        '        // src/extract_xgb_params.py from the model src/train_xgb_signal.py',
        '        // trains. This is a SEPARATE, advisory ML signal shown next to the',
        '        // deployed rule-based verdict above -- it does not feed calculateScore()',
        '        // or the Final Decision Engine, and nothing here changes an approval.',
        '        // On this data it does not beat the deployed scorecard, and the',
        '        // reject-inference augmentation it is trained on does not clearly help',
        '        // either -- see reports/xgb_signal_report.txt and',
        '        // reports/reject_inference_truth_report.txt.',
        f'        const XGB_FEATURES = {json.dumps(p["features"])};',
        f'        const XGB_TREES = {json.dumps(p["trees"], separators=(",", ":"))};',
        '',
        '        function xgbPredictProba(inputs) {',
        '            // XGBoost splits at float32 precision (its DMatrix is float32',
        '            // internally), so comparing at full JS double precision disagrees',
        '            // right at a threshold that sits exactly on a training value --',
        '            // Math.fround rounds both sides the same way XGBoost did. See',
        '            // extract_xgb_params.py\'s eval_tree for the case that caught this.',
        '            function walk(node, row) {',
        '                while (!(\'leaf\' in node)) {',
        '                    const v = row[node.f];',
        '                    const branch = Number.isFinite(v)',
        '                        ? (Math.fround(v) < Math.fround(node.th) ? \'yes\' : \'no\')',
        '                        : node.default;',
        '                    node = node[branch];',
        '                }',
        '                return node.leaf;',
        '            }',
        '            const row = XGB_FEATURES.map(f => inputs[f]);',
        '            let margin = 0;',
        '            for (const tree of XGB_TREES) margin += walk(tree, row);',
        f'            return 1 / (1 + Math.exp(-margin));  // base_score {p["base_score"]} is logit 0, folded in already',
        '        }',
        END,
        '',
    ]
    return '\n'.join(lines)


def main():
    if not os.path.exists(PARAMS):
        print(f'no {PARAMS} -- run src/extract_xgb_params.py first', file=sys.stderr)
        return 1
    p = json.load(io.open(PARAMS, encoding='utf-8'))

    s, crlf = load(HTML)
    block = build_block(p)

    pattern = re.compile(re.escape(BEGIN) + r'.*?' + re.escape(END) + r'\n', re.S)
    if pattern.search(s):
        s, n = pattern.subn(block, s)
        assert n == 1
        print('index.html          XGBoost block replaced in place')
    else:
        s, n = ANCHOR.subn(lambda m: m.group(1) + '\n' + block, s, count=1)
        assert n == 1, 'SCALER block not found to anchor the first insertion'
        print('index.html          XGBoost block inserted after SCALER')

    save(HTML, s, crlf)
    n_nodes = sum(_count(t) for t in p['trees'])
    print(f'  {len(p["trees"])} trees, {n_nodes} nodes')
    print()
    print('Now run: python -m pytest tests/test_xgb_signal.py')
    return 0


def _count(node):
    if 'leaf' in node:
        return 1
    return 1 + _count(node['yes']) + _count(node['no'])


if __name__ == '__main__':
    sys.exit(main())
